name: rick_and_morty
description: "Rick and Morty mobile app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: 7.6.4
  injectable: 2.3.2
  dartz: 0.10.1
  dio: 5.4.0
  json_annotation: 4.8.1
  flutter_bloc: 8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  dart_code_metrics: 5.7.6
  build_runner: 2.4.7
  injectable_generator: 2.4.1
  json_serializable: 6.7.1

flutter:
  uses-material-design: true
